### ISSUE TITLE
 Unknown method alias name: xmlschema => rfc3339

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/gem_rbs_collection#97]
I've just installed `rbs` with `rbs collection` in a new project, where I'm using `steep` and capping `activesupport` to `~> 6.0`due to a recent rails 7 bug with steep. After installing, I run `rbs validate` and I get the following error:

```
Validating class/module definition: `::Thread::SizedQueue`...
Validating class/module definition: `::ThreadGroup`...
Validating class/module definition: `::Time`...
bundler: failed to load command: rbs (/home/.bundle/ruby/3.0.0/bin/rbs)
/home/.bundle/ruby/3.0.0/gems/rbs-1.8.1/lib/rbs/definition_builder.rb:567:in `block in define_methods': .gem_rbs_collection/activesupport/6.0/activesupport-generated.rbs:6167:2...6167:25: Unknown method alias name: xmlschema => rfc3339 (::
Time) (RBS::UnknownMethodAliasError)
        from /home/.bundle/ruby/3.0.0/gems/rbs-1.8.1/lib/rbs/definition_builder/method_builder.rb:50:in `block in each'
        from /home/.rubies/ruby-3.0.1/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
....

**Comment by pocke** [comment]
It is a known issue and I fixed this problem in https://github.com/ruby/rbs/pull/808.
Please use the HEAD of rbs or wait to release a new version of RBS for Ruby 3.1.


Feel free to reopen the issue if the same error occurs with the patch.

Thanks.
